// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObservabilityDemo.Database;

#nullable disable

namespace ObservabilityDemo.Database.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObservabilityDemo.Database.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 5, 28),
                            Summary = "Balmy",
                            TemperatureC = 12
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 5, 29),
                            Summary = "Cool",
                            TemperatureC = -10
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2025, 5, 30),
                            Summary = "Cool",
                            TemperatureC = 37
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2025, 5, 31),
                            Summary = "Balmy",
                            TemperatureC = -10
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2025, 6, 1),
                            Summary = "Cool",
                            TemperatureC = -13
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
