global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  # - job_name: 'drizzle'
  #   static_configs:
  #     - targets: ['host.docker.internal:9091'] # hard-coded port matches launchSettings.json

  - job_name: "weather-api"
    static_configs:
      - targets: ["otel-collector:9464"]
